- name: Initial deployment of tv.pizzasuicideclub.com
  hosts: webservers
  remote_user: takosuke
  become: true
  vars:
  - app_name: tv.pizzasuicideclub.com
  - domain_name: tv.pizzasuicideclub.com
  - repo_path: "takosuke/tv.pizzasuicideclub.com"
  - repo_remote : origin
  - repo_version: master
  - webapps_dir: "/home/takosuke/public_html"

#  vars_prompt:
  roles:
  - clone_repo
  - log_setup
  - nginx_setup
  - pm2_setup
  - build_dependencies
