---

- name: install pm2
  npm: name=pm2 global=yes
#  notify: restart pm2
  become: yes
  become_method: sudo

- name: start app
  command: pm2 start server.js chdir={{ webapps_dir }}/{{ app_name }}/html/
  ignore_errors: yes

- name: make pm2 startup on boot
  command: pm2 startup -u {{ deploy_user }} -hp {{ webapps_dir }}/{{ app_name }}/html/
  become: yes
  become_method: sudo
  notify: reboot system
