---

- name: install pm2
  npm: name=pm2 global=yes
  notify: restart pm2
  become: yes
  become_method: sudo

- name: start app
  command: pm2 restart {{ webapps_dir }}/{{ app_name }}/html/server.js

- name: make pm2 startup on boot
  command: pm2 startup
  become: yes
  become_method: sudo
