---

- name: install pm2
  npm: name=pm2 global=yes
  notify: restart pm2

- name: start app
  command: pm2 start {{ webapps_dir }}/{{ app_name }}/html/server.js
#  become: true
#  become_user: takosuke

